### ISSUE TITLE
Can't save configs (on private bot using this repo)

### ISSUE THREAD

**Issue by chaun14** [SideProjectGuys/invite-manager-bot#118] opened 2019-09-02 08:13 UTC
I've setup a private bot using invitmanager's code.
Basic commands as help, prefix, ping and tracking system are working well.
When I try to setup somthing (!config leaveMessageChannel #mychannel) the bot with a freshly created databse send millions INSERT operations to the database but after few seconds the config is set.
With an bigger and older database the bot send billions INSERT request until discord timed out or the memory allocated to nodejs allocated memory is overloaded and the script crash 
![image](https://user-images.githubusercontent.com/42867004/64099624-07a51e80-cd6a-11e9-882d-4e7fe3a615cd.png)

the begin of the unwanted operation:
![image](https://user-images.githubusercontent.com/42867004/64099134-d5df8800-cd68-11e9-8ac4-35214ba570d6.png)

After reboot all configs are reset.

what i see in the console: https://i.imgur.com/9heQC6k.gifv

mariadb version: 10.2.26-MariaDB-10.2.26+maria~stretch
innodb_version:  5.7.27 
debian 9
node version: v11.15.0
npm version: 6.7.0

Is someting wrong in my server / bot configuration?
thanks for your help :)

**Comment by Valandur** [comment] 2019-09-02 08:56
The config object that the bot is inserting looks very wrong. It's supposed to be valid json, but that looks more like some kind of array converted to json. Does this happen with all config settings, or just the `joinMessageChannel`?
I don't think those are millions of insert statements, just one really long one, but there's obviously something wrong.

**Comment by chaun14** [comment] 2019-09-02 09:02
it happend in all configurations with  `config` and `interactiveConfig` commands

**Comment by chaun14** [comment] 2019-09-02 09:05
I am trying to use nodejs 10.16.3 but i got these error while connecting to discord 
![image](https://user-images.githubusercontent.com/42867004/64102997-65893480-cd71-11e9-998f-acd2a556b736.png)
![image](https://user-images.githubusercontent.com/42867004/64103018-72a62380-cd71-11e9-8f46-580c26e3beb3.png)
![image](https://user-images.githubusercontent.com/42867004/64103043-8487c680-cd71-11e9-95cf-d6f5ea6894e8.png)

**Comment by chaun14** [comment] 2019-09-02 15:56
for the error with Zlib just downgrade it to 0.1.4

**Comment by chaun14** [comment] 2019-09-02 16:00
i've try to run the bot with nodejs 10 but the same problem happen. It work fine with a new db but the problem restart at the second launch of the bot (configs are resetted)

**Comment by Valandur** [comment] 2019-09-02 16:56
Can you try with mysql instead of mariadb?
What character encoding is your database / the `settings` table / the `value` column in the settings table?

**Comment by chaun14** [comment] 2019-09-02 21:41
I can't install mysql-community-server on my vps. I've tried to use mariadb 10.3 but the problem happens. For the encoding I've kept it default

**Comment by Valandur** [comment] 2019-09-11 06:39
I'm afraid I can't reproduce this issue. I tested with node 10.16.3 and everything works fine, on Windows 10 and Ubuntu 18.04.

**Comment by chaun14** [comment] 2019-09-11 06:44
What database server have you used for your test?

**Comment by Valandur** [comment] 2019-09-11 06:58
MariaDB 10.4.7

**Comment by Valandur** [comment] 2019-09-11 09:05
So I was able to reproduce this issue now, it is most certainly a MariaDB issue. The insert works for me, but also produces weird column data like the one that you should. I believe it is related to this issue: https://github.com/sequelize/sequelize/issues/8702 that is fixed in sequelize v5, but this repo currently uses sequelize v4, and we are planning to switch to another ORM in the near future.

**Comment by chaun14** [comment] 2019-09-11 11:07
So for the official bot you are using mysql Community server?

**Comment by Valandur** [comment] 2019-09-11 11:52
Yes exactly, version 5.7.27

**Closed** 2019-10-10 00:06 UTC
Labels: type/bug, type/wontfix
